package com.myspace.gitproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class gitObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;

	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;

	public gitObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public gitObject(java.lang.String name, java.lang.String id,
			java.lang.Integer age) {
		this.name = name;
		this.id = id;
		this.age = age;
	}

}