package com.myspace.gitproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class gitObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public gitObject() {
    }




}